### PR TITLE
big integers

### PR DESCRIPTION
**Pull request by nevrome**
This PR introduces big integer values with package bit64 for the columns library.Quantification_pre-Indexing_total and library.Quantification_post-Indexing_total as discussed in #34 

```
library(sidora.core); library(tidyverse)
con <- get_pandora_connection(cred_file = ".credentials")
sites_df  <- get_df("TAB_Library", con) %>% convert_all_ids_to_values()
sites_df %>% filter(library.Full_Library_Id == "ARS001.A0101") %>% select(contains("Quantification"))
```

```
# A tibble: 1 x 2
  `library.Quantification_pre-Indexing_total` `library.Quantification_post-Indexing_total`
                                      <int64>                                      <int64>
1                                   377000000                                  40600000000
```

Please test! Some (!?) values are encoded in scientific notation in Pandora, so I had to transform this. This might be a source of error, so please check if this code is valid and produces the correct "amount of zeros".

I also want to point out again, that integer64 does not behave as expected for normal R users. I already ran into some weird and surprising effect with `unlist`. Please check the limitations section starting at page 9 here: https://cran.r-project.org/web/packages/bit64/bit64.pdf

### CODE REVIEW

**Comment by ivelsko** [comment]
I tried to test this but I still get NAs, so I must not have this update. I installed it again (`remotes::install_github("sidora-tools/sidora.core")`) and now have `sidora.core_0.0.0.9000`. What did I not do right?

**Comment by nevrome** [comment]
You have to install with `remotes::install_github("sidora-tools/sidora.core", ref = "big_int")` to get the version from this branch, I think. The necessary changes are not implemented in the main version yet.

**Comment by ivelsko** [comment]
This seems to half-way fix it. It looks like it has issues w/ fully written out numbers but is ok with numbers in scientific notation

```
remotes::install_github("sidora-tools/sidora.core", ref = "big_int")
library(sidora.core)
con <- get_pandora_connection(cred_file = "~/.credentials")

sites_df  <- get_df("TAB_Library", con) %>% convert_all_ids_to_values()

sites_df %>% 
  filter(library.Full_Library_Id %in% c("ARB002.A0101","ARS001.A0101","BAN001.A0101","BAN001.A0102", "CDM020.A0203")) %>% 
  select(contains(c("Full_Library_ID","Quantification"))) %>%
  arrange(library.Full_Library_Id)

# A tibble: 5 x 3
  library.Full_Library_Id `library.Quantification_pre-Indexing_total` `library.Quantification_post-Indexing_total`
  <chr>                                                       <int64>                                      <int64>
1 ARB002.A0101                                                     NA                                           NA
2 ARS001.A0101                                              377000000                                  40600000000
3 BAN001.A0101                                                     NA                                           NA
4 BAN001.A0102                                                     NA                                    295000000
5 CDM020.A0203                                                     NA                                           NA
```

Where I can see in Pandora online:
`ARB002.A0101` - pre&post both filled in, filled w/full numbers
`ARS001.A0101` - pre&post both filled in, filled w/scientific notation
`BAN001.A0101` - pre&post both filled in, filled w/full numbers
`BAN001.A0102` - only post filled in, filled w/scientific notation
`CDM020.A0203` - pre&post both filled in, filled w/full numbers

**Comment by nevrome** [comment]
Thanks for the feedback. Please try now. I get the following output now:

```
# A tibble: 5 x 3
  library.Full_Librar… `library.Quantification_pre-I… `library.Quantification_post-…
  <chr>                                       <int64>                        <int64>
1 ARB002.A0101                          1203300000000                 21475200000000
2 ARS001.A0101                              377000000                    40600000000
3 BAN001.A0101                               33900000                   267000000000
4 BAN001.A0102                                     NA                      295000000
5 CDM020.A0203                            11600000000                  5130000000000
```

**Comment by ivelsko** [comment]
Yes, I now get numbers where I expect them, and they have the correct number of 0s. I calculated the efficiency from the pre & post values and compared w/ the efficiency entered in Pandora. The values all checked out, so they're fine for arithmetic

**Review by ivelsko — APPROVED** [review]

**Comment by nevrome** [comment]
I think we can merge then, @jfy133?

**Comment by jfy133** [comment]
I've not had a chance to test but if Irina says it's ok, we can fix any other weird stuff when it crops up

**Comment by jfy133** [comment]
I've not had a chance to test but if Irina says it's ok, we can fix any other weird stuff when it crops up

**Pull request merged**
