### PR TITLE
Add list(s) of column types for all tables

### PR DESCRIPTION
**Pull request by jfy133**
This is a WIP, but would like feedback.

Would something like this be useful for validation and faster loading/filtering of data?

There are certain columns (Deleted, Ethically senstitive, Robot) that should be boolean values but currently are characters.

I also thought having lists of columns might help look up in other contexts (if you just take the names). These could be stored in a function such as fix_types (as suggested in https://github.com/sidora-tools/sidora.core/issues/5#issuecomment-584549960).

### CODE REVIEW

**Comment by nevrome** [comment]
Ah - excellent. We had something similar in c14bazAAR: [`enforce_types`](https://github.com/ropensci/c14bazAAR/blob/master/R/c14_date_list_enforce_types.R). Do you want to write it, @jfy133?

**Comment by jfy133** [comment]
I will try when I have a moment!

**Comment by jfy133** [comment]
@nevrome I've added the `enforce_types()` function now. However I don't seem to be able to implement it properly within `get_data.R` because I hit an error (`Error in !"Deleted" : invalid argument type`) when you do the deleted filter, I _think_ from line 25 on get_data.R? I see you're doing a sort of NSE but I couldn't get it to work with a logical. 

Maybe you could have alook

**Comment by nevrome** [comment]
I don't see how and why you got this error. Imho `enforce_types` should not go into `get_con`, but `get_df` in line 74: 

```
this_tab <- get_con(tab, con) %>% tibble::as_tibble() %>% enforce_types()
```

Type enforcing can only work reliably within R, not on the SQL server. 

Or am I missing something?

**Comment by nevrome** [comment]
The NSE is an unusual solution for me. My usual trick with the `.data` object (`.data$Deleted`) will not work with these connection objects.

**Comment by jfy133** [comment]
yeah, my idea

> I don't see how and why you got this error. Imho `enforce_types` should not go into `get_con`, but `get_df` in line 74:
> 
> ```
> this_tab <- get_con(tab, con) %>% tibble::as_tibble() %>% enforce_types()
> ```
> 
> Type enforcing can only work reliably within R, not on the SQL server.
> 
> Or am I missing something?

You are right, however my idea was to convert to tibble first and then do the filter, with the idea filtering the logical version of the `Deleted` column would be faster. But I guess it's only on load so fine for now. Re-pushed with just on the two lines you referred to.

Noted on the NSE

**Comment by nevrome** [comment]
Three things before I merge:

1. The example code in `enforce_types()` should go into `\dontrun{}`. Take a look at the travis check.
2. What is the purpose of this `playground/coltypes.R` file? Do you want to keep it as a reference?
3. Maybe you could mention this additional step in the documentation of `get_df()`. But maybe I should add some things to the documentation myself. You can as well leave this for me.

**Comment by jfy133** [comment]
> Three things before I merge:
> 
> 1. The example code in `enforce_types()` should go into `\dontrun{}`. Take a look at the travis check.
> 2. What is the purpose of this `playground/coltypes.R` file? Do you want to keep it as a reference?
> 3. Maybe you could mention this additional step in the documentation of `get_df()`. But maybe I should add some things to the documentation myself. You can as well leave this for me.

1. Ok, will fix
2. That should've been in `.gitignore`, don't know why it's there. I will remove it.
3. yes, will leave that to you so it's in one coherent message.

**Comment by jfy133** [comment]
@nevrome I think I've added /dontrun{} properly, but travis doesn't seem to have registered it? Could you hvae a look?

https://github.com/jfy133/sidora.core/blob/bcd27be84b6ed723157bae5152b659341410a229/R/enforce_types.R#L13-L23

**Comment by nevrome** [comment]
I think you forgot to update the documentation in `man/enforce_types.Rd`. Is this possible?

**Comment by nevrome** [comment]
I'll do it.

**Pull request merged**
