### PR TITLE
Add TL;DR quick reference

### PR DESCRIPTION
**Pull request by jfy133**

### CODE REVIEW

**Comment by nevrome** [comment]
Hm - I think this is less of a tl;dr than a just two additional commands. Maybe it's better to simply structure the quickstart guide with headlines and then add these two as well.

**Comment by jfy133** [comment]
I see what you mean (but I expect I would add more over time). On the otherhand I personally don't find quickstart so quickstart, I feel there is too much background description in there, and is rather better for a manual? I could try restructuring it a bit during S&B for example, instead?

**Comment by nevrome** [comment]
Go for it :+1: Thanks!

**Review by stschiff — APPROVED** [review]
Nice!

**Review by stschiff — APPROVED** [review]
Still OK :-)

**Review by stschiff — APPROVED** [review]

**Comment by nevrome** [comment]
`make_complete_table_list()` should probably also be mentioned in the quickstart guide. The division between "For users" and "For developers" is a bit arbitrary.

**Comment by jfy133** [comment]
Done as requested @nevrome

**Review by nevrome — APPROVED** [review]

**Pull request merged**
