### PR TITLE
Adds TAB_Analysis loading

### PR DESCRIPTION
**Pull request by jfy133**
Includes a prejoining function to bind the actual 'results string' table to the main results tab (as in the pandora webpage)

Also: get_df check for valid input tables, and warning message loading analysis can take a long time.

### CODE REVIEW

**Comment by nevrome** [comment]
I changed some stuff, @jfy133. Most importantly I tried to make sure that these helper functions `access_restricted_table` and `access_restricted_table` return connection objects and do not trigger any downloading by themselves. That's not their job as they are called by `get_con`.

I fixed/changed some more details. Please take a look and check if everything is still working. 

To make this PR complete we should probably also add the necessary changes to the join function, though I'm a bit worried that the purely hierarchical structure of Pandora breaks down at this lower levels. Is this the case? If you take a look at this: Do yourself a favor and merge the master into this branch before. I recently added TAB_Raw_Data to the join function.

**Comment by jfy133** [comment]
Thanks for looking @nevrome ! Will test and check.

Good point about the con, forgot the analysis table left join part could happen at the SQL request level (so to say).

I'm not sure what you mean about the joining and Pandora hierarchy thing though. Could you clarify?

**Comment by nevrome** [comment]
Nevermind, James. 3ae7616 does what I wanted. And it indeed seems to work like a charm :+1:

**Comment by jfy133** [comment]
Thanks for clarifying @nevrome. Thanks also for cleaning up that collection functions. I am still not fully understanding how to 'group' related functions together with the roxygen docs stuff (also the differentiation between external functions, internal functions, external functions with no rda), which is why that might have been a bit messy. Should talk about that at some point.

Just did a few personal tests and everything (as in all functions that have been modified) looks to be working as expected for me. I think we are good to go.

**Comment by nevrome** [comment]
Ready for a review? I think we can just merge at this point?

**Pull request merged**
